# Generated by Django 5.0.6 on 2024-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('adhar_no', models.CharField(max_length=12, unique=True)),
                ('id1', models.IntegerField(unique=True)),
            ],
        ),
    ]
